// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/book/dependencies.go

// Package mock_book is a generated GoMock package.
package book

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHttpResource is a mock of HttpResource interface.
type MockHttpResource struct {
	ctrl     *gomock.Controller
	recorder *MockHttpResourceMockRecorder
}

// MockHttpResourceMockRecorder is the mock recorder for MockHttpResource.
type MockHttpResourceMockRecorder struct {
	mock *MockHttpResource
}

// NewMockHttpResource creates a new mock instance.
func NewMockHttpResource(ctrl *gomock.Controller) *MockHttpResource {
	mock := &MockHttpResource{ctrl: ctrl}
	mock.recorder = &MockHttpResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpResource) EXPECT() *MockHttpResourceMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHttpResource) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHttpResourceMockRecorder) Do(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHttpResource)(nil).Do), req)
}