// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/book/external.go

// Package mock_book is a generated GoMock package.
package book

import (
	context "context"
	reflect "reflect"

	domain "gihub.com/gadhittana01/book-project/pkg/domain"
	gomock "github.com/golang/mock/gomock"
)

// Mockexternal is a mock of external interface.
type Mockexternal struct {
	ctrl     *gomock.Controller
	recorder *MockexternalMockRecorder
}

// MockexternalMockRecorder is the mock recorder for Mockexternal.
type MockexternalMockRecorder struct {
	mock *Mockexternal
}

// NewMockexternal creates a new mock instance.
func NewMockexternal(ctrl *gomock.Controller) *Mockexternal {
	mock := &Mockexternal{ctrl: ctrl}
	mock.recorder = &MockexternalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockexternal) EXPECT() *MockexternalMockRecorder {
	return m.recorder
}

// getBookByKey mocks base method.
func (m *Mockexternal) getBookByKey(ctx context.Context, req domain.GeBookByKeyReq) (domain.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getBookByKey", ctx, req)
	ret0, _ := ret[0].(domain.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getBookByKey indicates an expected call of getBookByKey.
func (mr *MockexternalMockRecorder) getBookByKey(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getBookByKey", reflect.TypeOf((*Mockexternal)(nil).getBookByKey), ctx, req)
}

// getListOfBooks mocks base method.
func (m *Mockexternal) getListOfBooks(ctx context.Context, req domain.GetListOfBooksReq) (domain.GetListOfBooksResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getListOfBooks", ctx, req)
	ret0, _ := ret[0].(domain.GetListOfBooksResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getListOfBooks indicates an expected call of getListOfBooks.
func (mr *MockexternalMockRecorder) getListOfBooks(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getListOfBooks", reflect.TypeOf((*Mockexternal)(nil).getListOfBooks), ctx, req)
}